swagger: "2.0"

info:
  version: 1.0.0
  title: Demo Rest API
  description: Demo de una Rest Api

schemes:
  - http
host: localhost:3000
basePath: /

paths: 
  /hello:
    # binds swagger app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition